INSERT INTO `member_info` (`first_name`, `last_name`, `status`) VALUES ( 'first name 1', 'last name 1', 'ACTIVE');
INSERT INTO `member_info` (`first_name`, `last_name`, `status`) VALUES ( 'first name 2', 'last name 2', 'ACTIVE');
INSERT INTO `member_info` (`first_name`, `last_name`, `status`) VALUES ( 'first name 3', 'last name 3', 'ACTIVE');
INSERT INTO `member_info` (`first_name`, `last_name`, `status`) VALUES ( 'first name 4', 'last name 4', 'ACTIVE');
INSERT INTO `member_info` (`first_name`, `last_name`, `status`) VALUES ( 'first name 5', 'last name 5', 'ACTIVE');
INSERT INTO `member_info` (`first_name`, `last_name`, `status`) VALUES ( 'first name 6', 'last name 6', 'ACTIVE');
INSERT INTO `member_info` (`first_name`, `last_name`, `status`) VALUES ( 'first name 7', 'last name 7', 'ACTIVE');
INSERT INTO `member_info` (`first_name`, `last_name`, `status`) VALUES ( 'first name 8', 'last name 8', 'ACTIVE');
INSERT INTO `member_info` (`first_name`, `last_name`, `status`) VALUES ( 'first name 9', 'last name 9', 'ACTIVE');
INSERT INTO `member_info` (`first_name`, `last_name`, `status`) VALUES ( 'first name 10', 'last name 10', 'ACTIVE');

INSERT INTO `claim_info` (`member_id`, `status`) VALUES ( 1, 'IN_PROGRESS');
INSERT INTO `claim_info` (`member_id`, `status`) VALUES ( 2, 'IN_PROGRESS');
INSERT INTO `claim_info` (`member_id`, `status`) VALUES ( 3, 'IN_PROGRESS');
INSERT INTO `claim_info` (`member_id`, `status`) VALUES ( 4, 'IN_PROGRESS');
INSERT INTO `claim_info` (`member_id`, `status`) VALUES ( 5, 'IN_PROGRESS');
INSERT INTO `claim_info` (`member_id`, `status`) VALUES ( 6, 'IN_PROGRESS');
INSERT INTO `claim_info` (`member_id`, `status`) VALUES ( 7, 'IN_PROGRESS');
INSERT INTO `claim_info` (`member_id`, `status`) VALUES ( 8, 'IN_PROGRESS');
INSERT INTO `claim_info` (`member_id`, `status`) VALUES ( 9, 'IN_PROGRESS');
INSERT INTO `claim_info` (`member_id`, `status`) VALUES ( 10, 'IN_PROGRESS');
